apiVersion: apps/v1
kind: Deployment
metadata:
  name: iso-share
  labels:
    app: iso-share
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iso-share
  template:
    metadata:
      labels:
        app: iso-share
    spec:
      containers:
      - name: iso-share
        image: iso-share:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: iso-share-secrets
              key: session-secret
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: iso-share-secrets
              key: admin-password
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: iso-share-uploads

---
apiVersion: v1
kind: Service
metadata:
  name: iso-share-service
spec:
  selector:
    app: iso-share
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iso-share-uploads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: iso-share-secrets
type: Opaque
data:
  # Base64 encoded values - update these!
  session-secret: c3VwZXJzZWNyZXRrZXk=  # supersecretkey
  admin-password: UEFTU1dPUkQ=          # PASSWORD