name: Build and Publish Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Diese Berechtigungen erlauben das Lesen der Inhalte und das Schreiben von Packages.
permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      # Repository-Code auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      # Docker Buildx einrichten
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Einloggen in die GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }
          # Verwende ein persönliches Zugriffstoken (PAT) als Secret (z.B. CR_PAT)
          password: ${{ secrets.CR_PAT }}

      # Docker Image bauen und pushen
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/julfoii/iso-share:latest
